  name: $device_name 
  platform: ESP32
  board: nodemcu-32s
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-build/$device_name/

  #esphomelib_version:
  #  local: /esphome-core 
