substitutions:
  device_name: !gen_device_name
  device_id: !gen_device_id
  mqtt_username: !gen_mqtt_username
  mqtt_password: !gen_mqtt_password
  # TODO: This should be generated? 
  prefix: water_supply
  fancy_prefix: Seedship Water Supply $device_id 

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

esphome: 
  name: $device_name 
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-build/$device_name/
  #arduino_version: 1.0.4
  #includes:
  #  - custom_components/dual_pot/dual_pot.h

sensor:
  - platform: adc
    pin: GPIO34
    name: $fancy_prefix Pump PSI
    state_topic: seedship/${prefix}_${device_id}/pump/psi
    icon: "mdi:water-pump"
    update_interval: 1s
    id: pump_psi
    attenuation: 11db
    expire_after: 60s
    force_update: true
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - calibrate_linear:
        # 200 PSI sensor
        - 0.5 -> 0.0
        - 1.14 -> 25.8
        - 1.37 -> 35.8
        - 1.85 -> 55.5
        - 3.09 -> 103.4
        - 3.28 -> 109.2
        ## 300 PSI sensor
        #- 0.5 -> 0.0
        #- 0.89 -> 25.4
        #- 1.35 -> 55
        #- 2.0 -> 93.3
        #- 2.1 -> 103.3
        #- 2.25 -> 110.4
    unit_of_measurement: "PSI"
    on_raw_value:
      then: 
        - sensor.template.publish:
            id: pump_raw_psi
            state: !lambda "return x;"

  - platform: template
    name: Seedship Water Supply $device_id Pump PSI Raw 
    accuracy_decimals: 4
    id: pump_raw_psi

  - platform: mqtt_subscribe
    name: Seedship Water Supply $device_id Pump PSI calibration slope
    id: pump_calibration_slope
    topic: seedship/$device_id/pump/psi_calibration_slope
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(pump_psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              filter->set_slope(x);
            }

  - platform: mqtt_subscribe
    name: Seedship Water Supply $device_id Pump PSI calibration bias
    id: pump_calibration_bias
    #seedship/ss_water_system/psi_calibration_bias
    topic: seedship/$device_id/psi_calibration_bias
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(pump_psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              filter->set_bias(x);
            }

#####
  - platform: adc
    pin: GPIO35
    name: Seedship Water Supply $device_id Bus PSI
    state_topic: seedship/$device_id/bus/psi
    icon: "mdi:water-pump"
    update_interval: 1s
    id: bus_psi
    #attenuation: 2.5db
    attenuation: 11db
    expire_after: 60s
    force_update: true
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - calibrate_linear:
        # 200 PSI sensor
        - 0.5 -> 0.0
        - 1.14 -> 25.8
        - 1.37 -> 35.8
        - 1.85 -> 55.5
        - 3.09 -> 103.4
        - 3.28 -> 109.2
        ## 300 PSI sensor
        #- 0.5 -> 0.0
        #- 0.89 -> 25.4
        #- 1.35 -> 55
        #- 2.0 -> 93.3
        #- 2.1 -> 103.3
        #- 2.25 -> 110.4
    unit_of_measurement: "PSI"
    on_raw_value:
      #then: 
      - sensor.template.publish:
          id: bus_raw_psi
          state: !lambda "return x;"
        #- mqtt.publish:
        #    topic: seedship/$device_id/pump/set_raw_psi
        #    payload: !lambda |-
        #      static char buff[7];
        #      return std::string(dtostrf(x,3,2,buff));
  # TODO: Update this via command rather than mqtt. 
  #- platform: custom

  - platform: template
    name: Seedship Water Supply $device_id Bus PSI Raw 
    accuracy_decimals: 4
    id: bus_raw_psi

  - platform: mqtt_subscribe
    name: Seedship Water Supply $device_id Bus PSI calibration slope
    id: bus_calibration_slope
    topic: seedship/$device_id/bus/psi_calibration_slope
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(bus_psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              filter->set_slope(x);
            }

  - platform: mqtt_subscribe
    name: Seedship Water Supply $device_id Bus PSI calibration bias
    id: bus_calibration_bias
    topic: seedship/$device_id/bus/psi_calibration_bias
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(bus_psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              filter->set_bias(x);
            }
####

  - platform: mqtt_subscribe
    name: Seedship $device_id PSI Manual
    state_topic: seedship/$device_id/psi_manual
    topic: seedship/$device_id/psi_manual_input
    accuracy_decimals: 2
    unit_of_measurement: "PSI"
# Enable logging
logger:
# Enable Over the Air Updates
ota:
