substitutions:
  #debug: !debug
  <<: !include templates/generated_substitutions.yaml

# This one is for light
i2c:
  - id: tsl2561_bus
    sda: GPIO23
    scl: GPIO22 

# This one is for CO2
  - id: scd30_bus
    sda: GPIO27
    scl: GPIO26
    scan: False
    frequency: 50kHz

spi:
  mosi_pin: GPIO15
  miso_pin: GPIO21
  clk_pin: GPIO2

light:
- platform: custom
  lambda: |-
    auto light_out = new dual_pot::DualPotLight();
    App.register_component(light_out);
    return {light_out};

  lights:
    - name: "${system_friendly} Lights"

text_sensor:
  - platform: mqtt_subscribe
    topic: seedship/${system}/root_zone_psi_calibration
    name: ${system_friendly} Root Zone PSI calibration 
    qos: 1
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              json::parse_json(x, 
                [filter](JsonObject &root) { 
                    ESP_LOGW(TAG, "JSON PARSED");
                    if (root.containsKey("slope"))
                      filter->set_slope(root["slope"]);
                    if (root.containsKey("bias"))
                      filter->set_bias(root["bias"]);
              });
            }
sensor:
  - platform: adc
    pin: GPIO34
    name: ${system_friendly} Root Zone PSI
    state_topic: seedship/${system}/root_zone_psi
    icon: "mdi:water-pump"
    update_interval: 1s
    id: psi
    attenuation: 11db
    expire_after: 60s
    force_update: true
    filters:
      #- or:
        #- delta: 10
        #- throttle: 1s
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      #- exponential_moving_average:
          #alpha: .1
          #send_every: 1
      - calibrate_linear:
        ## 300 PSI sensor
        #- 0.5 -> 0.0
        #- 0.89 -> 25.4
        #- 1.35 -> 55
        #- 2.0 -> 93.3
        #- 2.1 -> 103.3
        #- 2.25 -> 110.4
        # 200 PSI sensor
        - 0.5 -> 0.0
        - 1.14 -> 25.8
        - 1.37 -> 35.8
        - 1.85 -> 55.5
        - 3.09 -> 103.4
        - 3.28 -> 109.2
    unit_of_measurement: "PSI"
    on_raw_value:
      then: 
        - sensor.template.publish:
            id: raw_psi
            state: !lambda "return x;"
  - platform: template
    name: $system_friendly Root Zone PSI Raw 
    accuracy_decimals: 4
    unit_of_measurement: "raw"
    id: raw_psi

  - platform: dht
    model: DHT22
    pin: 
      number: GPIO19
    temperature:
      name: ${system_friendly} Ambiant Temperature
      state_topic: seedship/${system}/ambiant_temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${system_friendly} Ambiant Humidity
      state_topic: seedship/${system}/ambiant_humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 10s
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO18
    temperature:
      name: ${system_friendly} Shoot Zone Temperature
      id: shoot_zone_temp
      state_topic: seedship/${system}/shoot_zone_temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${system_friendly} Shoot Zone Humidity
      id: shoot_zone_humidity
      state_topic: seedship/${system}/shoot_zone_humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 10s
  - platform: template
    name: $system_friendly Shoot Zone VPD 
    accuracy_decimals: 2
    unit_of_measurement: "kPa"
    id: shoot_zone_vpd
    update_interval: 10s
    lambda: |- 
        return (1 - id(shoot_zone_humidity).state/100)*610.7*pow(10.0,(7.5 * id(shoot_zone_temp).state) / (237.3 + id(shoot_zone_temp).state) )/1000;

  - platform: dht
    model: DHT22
    pin: 
      number: GPIO5
    temperature:
      name: ${system_friendly} Root Zone Temperature
      state_topic: seedship/${system}/root_zone_temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${system_friendly} Root Zone Humidity
      state_topic: seedship/${system}/root_zone_humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s

  - platform: tsl2561
    i2c_id: tsl2561_bus
    name: ${system_friendly} Shoot Zone Lux
    state_topic: seedship/${system}/shoot_zone_lux
    update_interval: 0.5s
    expire_after: 75s
    filters:
        - or:
                - delta: 1
                - throttle: 30s
        - throttle: 0.01s

  - platform: scd30
    i2c_id: scd30_bus
    co2:
      name: "${system_friendly} Shoot Zone CO2"
      state_topic: seedship/${system}/shoot_zone_co2
      #accuracy_decimals: 1
    temperature:
      name: "${system_friendly} CO2 Temperature"
      state_topic: seedship/${system}/shoot_zone_co2_temperature
      #accuracy_decimals: 2
    humidity:
      name: "${system_friendly} CO2 Humidity"
      state_topic: seedship/${system}/shoot_zone_co2_humidity
      #accuracy_decimals: 1
    address: 0x61
    update_interval: 5s

esphome: 
  name: $device_name 
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-builds/$device_name/
  arduino_version: 1.0.4
  #includes:
  #  - custom_components/dual_pot/dual_pot.h

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml
# Enable logging
logger:
# Enable Over the Air Updates
ota:
