substitutions:
  device_name: !gen_device_name
  device_id: !gen_device_id
  mqtt_username: !gen_mqtt_username
  mqtt_password: !gen_mqtt_password
  prefix: seedship
  fancy_prefix: Seedship $device_id

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

esphome: 
  name: $device_name 
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-build/$device_name/
  arduino_version: 1.0.4
  includes:
    - custom_components/dual_pot/dual_pot.h

# This one is for light
i2c:
  - id: tsl2561_bus
    sda: GPIO23
    scl: GPIO22 

# This one is for CO2
  - id: scd30_bus
    sda: GPIO27
    scl: GPIO26
    scan: False
    frequency: 50kHz

spi:
  mosi_pin: GPIO15
  miso_pin: GPIO21
  clk_pin: GPIO2

light:
- platform: custom
  lambda: |-
    auto light_out = new dual_pot::DualPotLight();
    App.register_component(light_out);
    return {light_out};

  lights:
    - name: "${fancy_prefix} Lights"

text_sensor:
  - platform: mqtt_subscribe
    topic: seedship/${prefix}_$device_id/root_zone/psi_calibration
    name: $fancy_prefix Root Zone PSI calibration 
    qos: 1
    on_value:
      then:
        - lambda: |-
            static const char *TAG = "custom_sensor";
            CalibrateLinearFilter* filter = id(psi).get_filter<CalibrateLinearFilter>();

            if(filter == nullptr) {
              ESP_LOGW(TAG, "Could not find filter.");
            } else {
              ESP_LOGV(TAG, "Found filter! %s", typeid (filter).name());
              json::parse_json(x, 
                [filter](JsonObject &root) { 
                    ESP_LOGW(TAG, "JSON PARSED");
                    if (root.containsKey("slope"))
                      filter->set_slope(root["slope"]);
                    if (root.containsKey("bias"))
                      filter->set_bias(root["bias"]);
              });
            }
sensor:
  - platform: adc
    pin: GPIO34
    name: ${fancy_prefix} Root Zone PSI
    state_topic: seedship/${prefix}_$device_id/root_zone/psi
    icon: "mdi:water-pump"
    update_interval: 1s
    id: psi
    attenuation: 11db
    expire_after: 60s
    force_update: true
    filters:
      #- or:
        #- delta: 10
        #- throttle: 1s
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      #- exponential_moving_average:
          #alpha: .1
          #send_every: 1
      - calibrate_linear:
        ## 300 PSI sensor
        #- 0.5 -> 0.0
        #- 0.89 -> 25.4
        #- 1.35 -> 55
        #- 2.0 -> 93.3
        #- 2.1 -> 103.3
        #- 2.25 -> 110.4
        # 200 PSI sensor
        - 0.5 -> 0.0
        - 1.14 -> 25.8
        - 1.37 -> 35.8
        - 1.85 -> 55.5
        - 3.09 -> 103.4
        - 3.28 -> 109.2
    unit_of_measurement: "PSI"
    on_raw_value:
      then: 
        - sensor.template.publish:
            id: raw_psi
            state: !lambda "return x;"
  - platform: template
    name: $fancy_prefix Root Zone PSI Raw 
    accuracy_decimals: 4
    unit_of_measurement: "raw"
    id: raw_psi

  - platform: dht
    model: DHT22
    pin: 
      number: GPIO19
    temperature:
      name: ${fancy_prefix} Ambiant Temperature
      state_topic: seedship/${prefix}_$device_id/ambiant/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${fancy_prefix} Ambiant Humidity
      state_topic: seedship/${prefix}_$device_id/ambiant/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO18
    temperature:
      name: ${fancy_prefix} Shoot Zone Temperature
      state_topic: seedship/${prefix}_$device_id/shoot_zone/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${fancy_prefix} Shoot Zone Humidity
      state_topic: seedship/${prefix}_$device_id/shoot_zone/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO5
    temperature:
      name: ${fancy_prefix} Root Zone Temperature
      state_topic: seedship/${prefix}_$device_id/root_zone/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: ${fancy_prefix} Root Zone Humidity
      state_topic: seedship/${prefix}_$device_id/root_zone/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s

  - platform: tsl2561
    i2c_id: tsl2561_bus
    name: ${fancy_prefix} Shoot Zone Lux
    state_topic: seedship/${prefix}_$device_id/shoot_zone/lux
    update_interval: 0.5s
    expire_after: 75s
    filters:
        - or:
                - delta: 1
                - throttle: 30s
        - throttle: 0.01s

  - platform: scd30
    i2c_id: scd30_bus
    co2:
      name: "${fancy_prefix} Shoot Zone CO2"
      state_topic: seedship/${prefix}_$device_id/shoot_zone/co2
      #accuracy_decimals: 1
    temperature:
      name: "${fancy_prefix} CO2 Temperature"
      state_topic: seedship/${prefix}_$device_id/shoot_zone/co2_temperature
      #accuracy_decimals: 2
    humidity:
      name: "${fancy_prefix} CO2 Humidity"
      state_topic: seedship/${prefix}_$device_id/shoot_zone/co2_humidity
      #accuracy_decimals: 1
    address: 0x61
    update_interval: 5s

# Enable logging
logger:
# Enable Over the Air Updates
ota:
