substitutions:
  #debug: !debug
  <<: !include templates/generated_substitutions.yaml

# This one is for light
i2c:
  - id: tsl2561_bus
    sda: GPIO23
    scl: GPIO22

# This one is for CO2
  - id: scd30_bus
    sda: GPIO27
    scl: GPIO26
    scan: False
    frequency: 50kHz

spi:
  mosi_pin: GPIO15
  miso_pin: GPIO21
  clk_pin: GPIO2

light:
- platform: custom
  lambda: |-
    auto light_out = new dual_pot::DualPotLight();
    App.register_component(light_out);
    return {light_out};

  lights:
    - name: "${system_friendly} Shoot Zone Lights"

sensor:
  - platform: dht
    model: DHT22
    pin:
      number: GPIO18
    temperature:
      name: ${system_friendly} Shoot Zone Temperature
      id: shoot_zone_temp
      state_topic: seedship/${system}/shoot_zone_temperature
      expire_after: 5 min
      force_update: true
    humidity:
      name: ${system_friendly} Shoot Zone Humidity
      id: shoot_zone_humidity
      state_topic: seedship/${system}/shoot_zone_humidity
      expire_after: 5 min
      force_update: true
    update_interval: 1 min
  - platform: template
    name: $system_friendly Shoot Zone VPD
    accuracy_decimals: 2
    unit_of_measurement: "kPa"
    id: shoot_zone_vpd
    update_interval: 1 min
    expire_after: 5 min
    force_update: true
    lambda: |-
        return (1 - id(shoot_zone_humidity).state/100)*610.7*pow(10.0,(7.5 * id(shoot_zone_temp).state) / (237.3 + id(shoot_zone_temp).state) )/1000;

  - platform: dht
    model: DHT22
    pin: 
      number: GPIO5
    temperature:
      name: ${system_friendly} Root Zone Temperature
      state_topic: seedship/${system}/root_zone_temperature
      expire_after: 5 min
      force_update: true
    humidity:
      name: ${system_friendly} Root Zone Humidity
      state_topic: seedship/${system}/root_zone_humidity
      expire_after: 5 min
      force_update: true
    update_interval: 1 min

  - platform: tsl2561
    i2c_id: tsl2561_bus
    name: ${system_friendly} Shoot Zone Lux
    state_topic: seedship/${system}/shoot_zone_lux
    update_interval: 1 min
    expire_after: 5 min
    force_update: true

  - platform: scd30
    i2c_id: scd30_bus
    co2:
      name: "${system_friendly} Shoot Zone CO2"
      state_topic: seedship/${system}/shoot_zone_co2
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 1
    temperature:
      name: "${system_friendly} CO2 Temperature"
      state_topic: seedship/${system}/shoot_zone_co2_temperature
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 1
    humidity:
      name: "${system_friendly} CO2 Humidity"
      state_topic: seedship/${system}/shoot_zone_co2_humidity
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 1
    address: 0x61
    update_interval: 1 min

  - !include templates/sensor/seedship_mode_internal.yaml
  - platform: wifi_signal
    name: "${system_friendly} ${subsystem_friendly} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${system_friendly} ${subsystem_friendly} Uptime"

esphome:
  name: $device_name
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-builds/$device_name/
  arduino_version: 1.0.4
  #includes:
  #  - custom_components/dual_pot/dual_pot.h

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml
# Enable logging
logger:
# Enable Over the Air Updates
ota:
