substitutions:
  device_name: !gen_device_name
  device_id: !gen_device_id
  mqtt_username: !gen_mqtt_username
  mqtt_password: !gen_mqtt_password

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

esphome: 
  name: $device_name 
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-build/$device_name/
  arduino_version: 1.0.4
  includes:
    - custom_components/dual_pot/dual_pot.h

# This one is for light
i2c:
  - id: tsl2561_bus
    sda: GPIO23
    scl: GPIO22 

# This one is for CO2
  - id: scd30_bus
    sda: GPIO27
    scl: GPIO26
    scan: False
    frequency: 50kHz

spi:
  mosi_pin: GPIO15
  miso_pin: GPIO21
  clk_pin: GPIO2

light:
- platform: custom
  lambda: |-
    auto light_out = new dual_pot::DualPotLight();
    App.register_component(light_out);
    return {light_out};

  lights:
    - name: "Seedship $device_id Lights"

sensor:
  - platform: adc
    pin: GPIO34
    name: Seedship $device_id Root Zone PSI
    state_topic: seedships/$device_id/root_zone/psi
    icon: "mdi:water-pump"
    update_interval: 250ms
    attenuation: 2.5db
    expire_after: 60s
    filters:
      - or:
        - delta: 0.03
        - throttle: 30s
      - throttle: 0.1s
      #- sliding_window_moving_average:
      #    window_size: 7
      #    send_every: 2
        
      - exponential_moving_average:
          alpha: 0.1
          send_every: 4
      - offset: -0.44
      - multiply: 111.1111
    unit_of_measurement: "PSI"

  - platform: dht
    model: DHT22
    pin: 
      number: GPIO19
    temperature:
      name: Seedship $device_id Ambiant Temperature
      state_topic: seedships/$device_id/ambiant/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: Seedship $device_id Ambiant Humidity
      state_topic: seedships/$device_id/ambiant/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO18
    temperature:
      name: Seedship $device_id Shoot Zone Temperature
      state_topic: seedships/$device_id/shoot_zone/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: Seedship $device_id Shoot Zone Humidity
      state_topic: seedships/$device_id/shoot_zone/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO5
    temperature:
      name: Seedship $device_id Root Zone Temperature
      state_topic: seedships/$device_id/root_zone/temperature
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    humidity:
      name: Seedship $device_id Root Zone Humidity
      state_topic: seedships/$device_id/root_zone/humidity
      expire_after: 75s
      filters:
          - or:
                  - delta: 1
                  - throttle: 30s
          - throttle: 0.5s
    update_interval: 1s

  - platform: tsl2561
    i2c_id: tsl2561_bus
    name: Seedship $device_id Shoot Zone Lux
    state_topic: seedships/$device_id/shoot_zone/lux
    update_interval: 0.5s
    expire_after: 75s
    filters:
        - or:
                - delta: 1
                - throttle: 30s
        - throttle: 0.01s

  - platform: scd30
    i2c_id: scd30_bus
    co2:
      name: "Seedship $device_id Shoot Zone CO2"
      state_topic: seedships/$device_id/shoot_zone/co2
      #accuracy_decimals: 1
    temperature:
      name: "Seedship $device_id CO2 Temperature"
      state_topic: seedships/$device_id/shoot_zone/co2_temperature
      #accuracy_decimals: 2
    humidity:
      name: "Seedship $device_id CO2 Humidity"
      state_topic: seedships/$device_id/shoot_zone/co2_humidity
      #accuracy_decimals: 1
    address: 0x61
    update_interval: 5s

# Enable logging
logger:
# Enable Over the Air Updates
ota:
