substitutions:
  #debug: !debug
  <<: !include templates/generated_substitutions.yaml

wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

esphome:
  name: $device_name
  platform: ESP32
  board: esp32doit-devkit-v1
  # If it builds in the /config folder like is default, then there arise
  # conflicts between the server and my machine. /tmp/esphome-build is a volume.
  build_path: /tmp/esphome-builds/$device_name/
  #arduino_version: 1.0.4
  #includes:
  #  - custom_components/dual_pot/dual_pot.h

i2c:
  # This one is for CO2
  - id: scd30_bus
    sda: GPIO27
    scl: GPIO26
    scan: False
    frequency: 50kHz

sensor:
  - !include templates/sensor/seedship_mode.yaml

  - platform: mqtt_subscribe
    name: $system_friendly PSI Manual
    state_topic: seedship/${system}/psi_manual
    topic: seedship/${system}/psi_manual_input
    accuracy_decimals: 2
    unit_of_measurement: "PSI"

  - platform: adc
    pin: GPIO34
    name: $system_friendly Pump PSI
    state_topic: seedship/${system}/pump_psi
    icon: "mdi:water-pump"
    id: pump_psi
    update_interval: 1s
    expire_after: 60s
    force_update: true
    attenuation: 11db
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 5
      - calibrate_linear:
          raw_sensor:
            name: $system_friendly Pump PSI Raw
            id: pump_psi_raw
          calibration_sensor:
              name: $system_friendly Pump PSI Calibration
              topic: seedship/${system}/pump_psi_calibration
          datapoints:
            # 200 PSI sensor
            - 0.5 -> 0.0
            - 1.14 -> 25.8
            - 1.37 -> 35.8
            - 1.85 -> 55.5
            - 3.09 -> 103.4
            - 3.28 -> 109.2
            ## 300 PSI sensor
            #- 0.5 -> 0.0
            #- 0.89 -> 25.4
            #- 1.35 -> 55
            #- 2.0 -> 93.3
            #- 2.1 -> 103.3
            #- 2.25 -> 110.4
    unit_of_measurement: "PSI"

  - platform: adc
    pin: GPIO35
    name: $system_friendly Bus PSI
    state_topic: seedship/${system}/bus_psi
    icon: "mdi:water-pump"
    id: bus_psi
    update_interval: 1s
    expire_after: 60s
    force_update: true
    attenuation: 11db
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 5
      - calibrate_linear:
          raw_sensor:
            name: $system_friendly Bus PSI Raw
            id: bus_psi_raw
          calibration_sensor:
              name: $system_friendly Bus PSI Calibration
              topic: seedship/${system}/bus_psi_calibration
          datapoints:
            # 200 PSI sensor
            - 0.5 -> 0.0
            - 1.14 -> 25.8
            - 1.37 -> 35.8
            - 1.85 -> 55.5
            - 3.09 -> 103.4
            - 3.28 -> 109.2
            ## 300 PSI sensor
            #- 0.5 -> 0.0
            #- 0.89 -> 25.4
            #- 1.35 -> 55
            #- 2.0 -> 93.3
            #- 2.1 -> 103.3
            #- 2.25 -> 110.4
    unit_of_measurement: "PSI"

  - platform: scd30
    i2c_id: scd30_bus
    co2:
      name: "${system_friendly} Ambient CO2"
      state_topic: seedship/${system}/ambient_co2
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 0
    temperature:
      name: "${system_friendly} Ambient CO2 Temperature"
      state_topic: seedship/${system}/ambient_co2_temperature
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 1
    humidity:
      name: "${system_friendly} Ambient CO2 Humidity"
      state_topic: seedship/${system}/ambient_co2_humidity
      expire_after: 5 min
      force_update: true
      accuracy_decimals: 1
    address: 0x61
    update_interval: 1 min

# Enable logging
logger:
# Enable Over the Air Updates
ota:
