# This is an unbranded-seedship-shoot-zone-power.yaml template.
substitutions:
  device_name: !gen_device_name
  device_id: !gen_device_id
  delay: !gen_delay 15
  mqtt_username: !gen_mqtt_username
  mqtt_password: !gen_mqtt_password
  prefix: seedship
  fancy_prefix: Seedship $device_id Shoot Zone

esphome: !include templates/esphome/esp01_1m.yaml
wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

switch:
  - platform: gpio
    name: "${fancy_prefix} Cooling"
    command_topic: seedship/${prefix}_$device_id/shoot_zone/cooling
    pin: GPIO15
    #inverted: yes
    # Relay 1
    id: relay1
  - platform: gpio
    name: "${fancy_prefix} Dehumidification"
    command_topic: seedship/${prefix}_$device_id/shoot_zone/dehumidification
    pin: GPIO5
    #inverted: yes
    # Relay 2 
    id: dehumidifier
  - platform: gpio
    name: "${fancy_prefix} Heating"
    command_topic: seedship/${prefix}_$device_id/shoot_zone/heater
    pin: GPIO14
    #inverted: yes
    # Relay 3
    id: heater_switch
  - platform: gpio
    # Relay 4
    name: "${fancy_prefix} Lighting"
    command_topic: seedship/${prefix}_$device_id/shoot_zone/light
    pin: GPIO12
    #inverted: yes
    id: lights
  - platform: gpio
    name: "${fancy_prefix} USB Power"
    command_topic: seedship/${prefix}_$device_id/shoot_zone/usb_power
    pin: GPIO4
    restore_mode: ALWAYS_ON
    id: relay5

  - platform: template
    name: "${fancy_prefix} Heater"
    id: heater
    #icon: "mdi:spray"
    lambda: |-
      if (id(heater).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: heater_switch
      - delay: 5min
      - switch.turn_off: heater_switch
      # Give the heater a chance to cool. 
      - delay: 5min

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: False
    name: "${fancy_prefix} Button"

  - platform: status
    name: "${fancy_prefix} Status"

sensor:
  - platform: wifi_signal
    name: "${fancy_prefix} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${fancy_prefix} Uptime"


  - platform: mqtt_subscribe
    name: "${fancy_prefix} Temperature"
    id: shoot_zone_temperature
    topic: seedship/${prefix}_$device_id/shoot_zone/temperature
    on_value:
      then:
        - if:
            condition:
              and:
                  - sensor.in_range:
                      id: shoot_zone_temperature
                      below: 19.0
                  - switch.is_off: heater
                  - mqtt.connected:
                  # Detect NaN
                  # Detect Unavalible. 
                  #- shoot_zone_temperature_time < 1 minute. Or maybe short MQTT death and just detect connection to MQTT.
            then:
              - switch.turn_on: heater
              #- delay: 5min
              #- switch.turn_off: heater
        - if:
            condition:
              and:
                  - sensor.in_range:
                      id: shoot_zone_temperature
                      above: 21.0
                  - switch.is_on: heater
                  # Detect NaN
                  # Detect Unavalible. 
                  #- shoot_zone_temperature_time < 1 minute. Or maybe short MQTT death and just detect connection to MQTT.
            then:
              - switch.turn_off: heater
    
  - platform: mqtt_subscribe
    name: "${fancy_prefix} Humidity"
    id: shoot_zone_humidity
    topic: seedship/${prefix}_$device_id/shoot_zone/humidity
    on_value:
        then:
          - if:
              condition:
                and:
                    - sensor.in_range:
                        id: shoot_zone_humidity
                        above: 75
                    - switch.is_off: dehumidifier
                    - mqtt.connected:
              then:
                - switch.turn_on: dehumidifier
          - if:
              condition:
                and:
                    - sensor.in_range:
                        id: shoot_zone_humidity
                        below: 60
                    - switch.is_on: dehumidifier
              then:
                - switch.turn_off: dehumidifier

text_sensor:
  - platform: version
    name: "${fancy_prefix} ESPHome Version"  

time:
  - platform: sntp
    # Will turn lights on every 5 minutes from 22:00-9:55. Could also add if: switch.is_off: lights with some potential workarounds?
    timezone: America/Denver
    on_time:
      - seconds: 0
        minutes: 0,5,10,15,20,25,30,35,40,45,50,55
        hours: 22,23,0,1,2,3,4,5,6,7,8,9
        then: 
          if:
            condition:
              switch.is_off: lights
            then:
              - delay: $delay
              - switch.turn_on: lights
              
  - platform: sntp
    # Will turn lights off every 5 minutes from 10:00-21:55.
    timezone: America/Denver
    on_time:
      - seconds: 0
        minutes:  0,5,10,15,20,25,30,35,40,45,50,55
        hours: 10,11,12,13,14,15,16,17,18,19,20,21
        then:
          if:
            condition:
              switch.is_on: lights
            then:
              - delay: $delay
              - switch.turn_off: lights

status_led:
  pin:
    number: GPIO2

logger:
ota:
