# This is a hal-humidity-temperature.yaml template.
substitutions:
  device_name: !gen_device_name
  device_id: !gen_device_id
  mqtt_username: !gen_mqtt_username
  mqtt_password: !gen_mqtt_password

esphome: !include templates/esphome/esp01_1m.yaml
wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml

switch:
  - platform: gpio
    name: "Seedship ${device_id} Shoot Zone Cooling"
    command_topic: seedship/$device_id/shoot_zone/cooling
    pin: GPIO15
    #inverted: yes
    # Relay 1
    id: relay1
  - platform: gpio
    name: "Seedship ${device_id} Shoot Zone Dehumidification"
    command_topic: seedship/$device_id/shoot_zone/dehumidification
    pin: GPIO5
    #inverted: yes
    # Relay 2 
    id: dehumidifier
  - platform: gpio
    name: "Seedship ${device_id} Shoot Zone Heating"
    command_topic: seedship/$device_id/shoot_zone/heater
    pin: GPIO14
    #inverted: yes
    # Relay 3
    id: heater_switch
  - platform: gpio
    # Relay 4
    name: "Seedship ${device_id} Shoot Zone Lighting"
    command_topic: seedship/$device_id/shoot_zone/light
    pin: GPIO12
    #inverted: yes
    id: lights
  - platform: gpio
    name: "Seedship ${device_id} Shoot Zone USB Power"
    command_topic: seedship/$device_id/shoot_zone/usb_power
    pin: GPIO4
    restore_mode: ALWAYS_ON
    id: relay5

  - platform: template
    name: "Seedship ${device_id} Heater"
    id: heater
    #icon: "mdi:spray"
    lambda: |-
      if (id(heater).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: heater_switch
      - delay: 5min
      - switch.turn_off: heater_switch
      # Give the heater a chance to cool. 
      - delay: 5min

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: False
    name: "Seedship ${device_id} Shoot Zone Power Button"
    on_press:
      - switch.toggle: relay1
      - switch.toggle: dehumidifier
      - switch.toggle: heater_switch
      - switch.toggle: lights

  - platform: status
    name: "Seedship ${device_id} Shoot Zone Power Status"

sensor:
  - platform: wifi_signal
    name: "Seedship ${device_id} Shoot Zone Power WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Seedship ${device_id} Shoot Zone Power Uptime"

  - platform: mqtt_subscribe
    name: "Seedship Shoot Zone Temperature"
    id: shoot_zone_temperature
    topic: seedship/$device_id/shoot_zone/temperature
    on_value:
      then:
        - if:
            condition:
              and:
                  - sensor.in_range:
                      id: shoot_zone_temperature
                      below: 19.0
                  - switch.is_off: heater
                  - mqtt.connected:
                  # Detect NaN
                  # Detect Unavalible. 
                  #- shoot_zone_temperature_time < 1 minute. Or maybe short MQTT death and just detect connection to MQTT.
            then:
              - switch.turn_on: heater
              #- delay: 5min
              #- switch.turn_off: heater
        - if:
            condition:
              and:
                  - sensor.in_range:
                      id: shoot_zone_temperature
                      above: 21.0
                  - switch.is_on: heater
                  # Detect NaN
                  # Detect Unavalible. 
                  #- shoot_zone_temperature_time < 1 minute. Or maybe short MQTT death and just detect connection to MQTT.
            then:
              - switch.turn_off: heater
    
  - platform: mqtt_subscribe
    name: "Seedship Shoot Zone Humidity"
    id: shoot_zone_humidity
    topic: seedship/$device_id/shoot_zone/humidity
    on_value:
        then:
          - if:
              condition:
                and:
                    - sensor.in_range:
                        id: shoot_zone_humidity
                        above: 75
                    - switch.is_off: dehumidifier
                    - mqtt.connected:
              then:
                - switch.turn_on: dehumidifier
          - if:
              condition:
                and:
                    - sensor.in_range:
                        id: shoot_zone_humidity
                        below: 60
                    - switch.is_on: dehumidifier
              then:
                - switch.turn_off: dehumidifier

text_sensor:
  - platform: version
    name: "Seedship ${device_id} Shoot Zone Power ESPHome Version"  

status_led:
  pin:
    number: GPIO2

logger:
ota:
