# This is an unbranded-water-supply-mixer.yaml template. 
substitutions:
  #debug: !debug
  <<: !include templates/generated_substitutions.yaml

script:
  - id: fertigate_strawberries
    then:
      - logger.log: "Starting Furtigation"
      - lambda: |-
          id(mixers).dose();
      - delay: 2min
      - lambda: |-
          id(part_a).dose();
      - wait_until:
          switch.is_off: part_a
      - delay: 5min
      - lambda: |-
          id(part_b).dose();
      - wait_until:
          switch.is_off: part_b
      - delay: 2min
      - lambda: |-
          id(ph_up).dose();
      - delay: 120s

switch:
  # Relay 1
  - platform: dosage
    name: "${system_friendly} Part A"
    command_topic: seedship/${system}/part_a
    pin: GPIO15
    id: part_a
    exact_timing: true
    dosage: 10s

  # Relay 2
  - platform: dosage
    name: "${system_friendly} Part B"
    command_topic: seedship/${system}/part_b
    pin: GPIO5
    id: part_b
    exact_timing: true
    dosage: 10s

  # Relay 3
  - platform: dosage
    name: "${system_friendly} PH Up"
    command_topic: seedship/${system}/ph_up
    pin: GPIO14
    id: ph_up
    dosage: 10s

  # Relay 4
  - platform: dosage
    name: "${system_friendly} PH Down"
    command_topic: seedship/${system}/ph_down
    pin: GPIO12
    id: water
    dosage: 60s

  # Relay USB
  - platform: dosage
    name: "${system_friendly} Mixers"
    command_topic: seedship/${system}/mixers
    pin: GPIO4
    id: mixers
    dosage: 30min

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${system_friendly} ${subsystem_friendly} Button"
    # TODO: Add logic for long click to toggle mixers.
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 0.3s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double-Clicked"
          - if:
              condition:
                - script.is_running: fertigate_strawberries
              then:
                - logger.log: Already mixing strawberry food. Canceling job.
                - script.stop: fertigate_strawberries
                - lambda: |-
                    id(part_a).cancel_dose();
                    id(part_b).cancel_dose();
                    id(ph_up).cancel_dose();
                    id(ph_down).cancel_dose();
                    id(mixers).cancel_dose();
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single-Clicked"
          - mqtt.publish:
              topic: seedship/${system}/strawberries
              payload: 1

  - platform: status
    name: "${system_friendly} ${subsystem_friendly} Status"

sensor:
  - platform: mqtt_subscribe
    id: strawberry
    topic: seedship/${system}/strawberries
    on_value:
      - if:
          condition:
            and:
                - script.is_running: fertigate_strawberries
          then:
            - logger.log: Already mixing strawberry food. Exiting.
          else:
            - logger.log: Fertigating
            - script.execute: fertigate_strawberries

  #- !include templates/sensor/seedship_mode.yaml
  - platform: wifi_signal
    name: "${system_friendly} ${subsystem_friendly} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${system_friendly} ${subsystem_friendly} Uptime"

text_sensor:
  - platform: version
    name: "${system_friendly} ${subsystem_friendly} ESPHome Version"  

status_led:
  pin:
    number: GPIO2

esphome: !include templates/esphome/esp01_1m.yaml
wifi: !include secrets/wifi.yaml
mqtt: !include templates/mqtt/mqtt.yaml
logger:
ota:
